- name: enable sshd service
  when: ansible_distribution == 'FreeBSD'
  lineinfile: dest=/etc/rc.conf regexp=^sshd_enable= line=sshd_enable=YES

- name: Paste sshd config
  template: src=sshd_config dest=/etc/ssh/sshd_config
  notify: restart sshd
